### ISSUE TITLE
Implement Dark Mode

### ISSUE THREAD

**Issue by KriteshTimsina** [KriteshTimsina/Wassupbroo-Chat-App#1]
Under completion:
- user can toggle between dark and light mode
- user preferences gets saved to local storage

Feel feel to use any library of your choice.
I suggest next-themes

**Comment by Sweetdevil144** [comment]
Is the issue open ?

**Comment by KriteshTimsina** [comment]
Yes

**Comment by Sweetdevil144** [comment]
Great. I'm on it then !! 
--
**Can you assign this to me ?**

**Comment by Sweetdevil144** [comment]
I'm so sorry @KriteshTimsina.
Unfortunately, I can't fix the issue now due to medical reasons.
Thanks for the opportunity😊

**Comment by KriteshTimsina** [comment]
Take care mate !

**Comment by Itezaz-ul-Hassan** [comment]
@KriteshTimsina I would like to work on it. Assign this issue to me

**Comment by Itezaz-ul-Hassan** [comment]
@KriteshTimsina Dark mode implemented in this [PR](https://github.com/KriteshTimsina/Wassupbroo-Chat-App/pull/5)

**Comment by KriteshTimsina** [comment]
@Itezaz-ul-Hassan I've merged this PR but could you change the following:
-change icons to something else that doesn't fit well with the UI, or remove that white background
- ChatFooter input field text is not visible in dark mode
-try making emoji picker dark in dark mode
-landing page image is white in dark mode

You can create a separate issue and work on it.
