### ISSUE TITLE
[Feature] Implement room join message

### ISSUE THREAD

**Issue by KriteshTimsina** [KriteshTimsina/Wassupbroo-Chat-App#12]
When someone enters a chatrrom and start a conversation, display a message "{NAME} joined a chat".
![image](https://github.com/KriteshTimsina/Wassupbroo-Chat-App/assets/103115789/874a3914-daf0-4882-9387-16306f08be24)

**Comment by sushma1031** [comment]
Hello, I'd like to work on this as part of Hacktoberfest, could you please assign it to me?

**Comment by KriteshTimsina** [comment]
Sure !
