### ISSUE TITLE
Add emoji picker in chat

### ISSUE THREAD

**Issue by KriteshTimsina** [KriteshTimsina/Wassupbroo-Chat-App#2]
Use any package that enables user to pick emojis and when pressed on emojis, it must be available in input field.

something like this:

https://github.com/KriteshTimsina/Wassupbroo-Chat-App/assets/103115789/9a93e2fb-363e-4594-8270-6482876ed66e

**Comment by Namatuzio** [comment]
Hi, I'll tackle this issue!

**Comment by KriteshTimsina** [comment]
Great! Work on it
