### ISSUE TITLE
Revamp Landing Page

### ISSUE THREAD

**Issue by KriteshTimsina** [KriteshTimsina/Wassupbroo-Chat-App#4]
The current landing page looks terrible. Feel free to design a better landing page as you like.

**Comment by shivaram19** [comment]
could you please assign this task to me @KriteshTimsina ?
Thank you !

**Comment by KriteshTimsina** [comment]
Done ! You may work on it

**Comment by KriteshTimsina** [comment]
@shivaram19 any updates?

**Comment by shivaram19** [comment]
> @shivaram19 any updates?

yeah @KriteshTimsina ,I was making a design and searching for the appropriate background and gifs ,adding ideas to them ,I'll share the design tomorrow @12 pm
